image:
  repository: ghcr.io/acdh-oeaw/qos-script/qos-script
  tag: latest

ingress:
  enabled: false

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

startupProbe:
  enabled: false
