image:
  repository: ghcr.io/acdh-oeaw/qos-script/qos-script:latest

service:
  name: qos-script

ingress:
  enabled: false

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

startupProbe:
  enabled: false
